# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#
# filer
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

[[plugins]]
repo = 'junegunn/fzf'
build = './install.sh --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
command! -bang -nargs=? -complete=dir Files
  \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'source': 'ag --hidden --ignore .git -g ""'}), <bang>0)
'''


[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#
# themes
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='term'
let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'joshdick/onedark.vim'


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#
# syntax
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'ianks/vim-tsx'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
depends = ['vim-javascript']

[[plugins]]
repo = 'posva/vim-vue'


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#
# linter
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_sign_error = '>'
let g:ale_sign_warning = '-'
let g:ale_cache_executable_check_failures = 1
let g:ale_open_list = 0
let g:ale_set_highlights = 1
let g:ale_linter_aliases = {
\ 'javascript.jsx': ['css', 'javascript.jsx'],
\ 'typescript': ['css', 'typescript']
\}

let g:ale_linters = {
\ 'javascript': ['eslint'],
\ 'javascript.jsx': ['stylelint', 'eslint'],
\ 'typescript': ['stylelint', 'tslint'],
\ 'ruby': ['rubocop'], 
\ 'css': ['stylelint'], 
\ 'scss': ['stylelint'], 
\ 'sass': ['stylelint'], 
\ 'nerdtree': ''
\}
'''


# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#
# LSP
# _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
